version: "3"

services:
  db:
    image: postgres:latest
    env_file:
      env/.postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  todo-gateway: &todo
    build: .
    environment:
      call_downstream: 1
      downstream: "http://todo-downstream:5000"
    env_file:
      - env/.env
      - env/.postgres
    depends_on:
      - db
    ports:
      - "5000"
    volumes:
      - ./:/code


  todo-downstream:
    <<: *todo
    environment:
      call_downstream: 0

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - todo-gateway
    ports:
      - "4000:4000"
